name: Semver Extract
description: >
  Work with Semantic Versions.
inputs:
  version:
    description: The current version passed as an input to the action.
    required: false
  package-manager-type:
    description: >
      The type of package manager. One of maven, npm. Used to collect the current version from the package manager file
      associated with that package manager (e.g. npm => package.json, maven = pom.xml, etc.).
    required: false
  bump:
    description: >
      The type of version increment (e.g. patch, minor, major, prerelease, etc.). This action is READ-ONLY for the
      filesystem.
    required: false
  prerelease-id:
    description: >
      The prerelease identifier used for versiono icrement.
    required: false
outputs:
  snapshot-release:
    description: Whether the version is a SNAPSHOT
  version:
    description: The current version.
  major:
    description: The current MAJOR version.
  minor:
    description: The current MINOR version.
  patch:
    description: The current PATCH version.
  prerelease:
    description: The current PRERELEASE ID.
  next-version:
    description: The version used to next.
  next-major:
    description: The next MAJOR version.
  next-minor:
    description: The next MINOR version.
  next-patch:
    description: The next PATCH version.
  next-snapshot-version:
    description: the next SNAPSHOT version to set after the build.
  next-snapshot-major:
    description: The next SNAPSHOT MAJOR version.
  next-snapshot-minor:
    description: The next SNAPSHOT MINOR version.
  next-snapshot-patch:
    description: The next SNAPSHOT PATCH version.

branding:
  icon: package
  color: blue
runs:
  using: node12
  main: dist/index.js
